package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Заполнить форму обратного звонка")
    void generatedTest() {
        step("Перейти на сайт https://orbitsoft.com/ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("Перейти по кнопке Обратный звонок", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить форму", () -> {
            step("// todo: just add selenium action");
        });

        step("Отправить форму", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://orbitsoft.com/ru/'", () ->
            open("https://orbitsoft.com/ru/"));

        step("Page title should have text 'OrbitSoft - Мы создаем инновационные технологии для рынка интернет-рекламы'", () -> {
            String expectedTitle = "OrbitSoft - Мы создаем инновационные технологии для рынка интернет-рекламы";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://orbitsoft.com/ru/'", () ->
            open("https://orbitsoft.com/ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}